---
- hosts: app
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker', 'docker-compose']
    - git:
        repo: https://github.com/ColinRoye/mongo_deployment
        dest: /app
        force: yes
    - name: Run mix commands
      shell: cd /app
          && sudo su && docker system prune
          && sudo sysctl -w vm.max_map_count=524288
          && sudo nohup docker-compose up --build&
      ignore_errors: yes
      #loop:
      #  - "do deps.get, compile"
      #  - "ecto.create"
      #  - "ecto.migrate"
      become: True
