---
- hosts: app
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker', 'docker-compose']
    - git:
        repo: https://github.com/ColinRoye/mongo_deployment
        dest: /app
        force: yes
    - name: Run mix commands
      shell: cd /app
               && echo y | sudo docker system prune
               && sudo rm -rd /disk01/data
               && sudo sysctl -w vm.max_map_count=524288
               && npm install
               && sudo docker-compose down
               && sudo nohup docker-compose up&
      #loop:
      #  - "do deps.get, compile"
      #  - "ecto.create"
      #  - "ecto.migrate"
      become: True
